[package]
name = "chimeralm"
version = "0.1.0"
edition = "2024"

[lib]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
name = "chimeralm"
crate-type = ["cdylib", "rlib"]

[dependencies]
deepbiop = { git = "https://github.com/cauliyang/DeepBioP", branch = "main", features = [
  "fastq",
  "bam",
  "utils",
] }
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.11.0" }
thiserror = "2.0.20"
anyhow = "1.0.104"
walkdir = { version = "2.5.0" }
rayon = { version = "1.12.0" }
pyo3 = { version = "0.23.5", features = [
  "abi3-py310",
  "extension-module",
  "anyhow",
] }

ctrlc = "3.5"
log = "0.4"
pyo3-log = "0.12"
noodles = { version = "0.116.0", features = [
  "bgzf",
  "core",
  "csi",
  "fasta",
  "fastq",
  "sam",
  "bam",
] }
bio = "4.0.1"

ahash = "0.8.12"
numpy = "0.23"
ndarray = { version = "0.16", features = ["serde", "rayon"] }
num-traits = { version = "0.2" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.10.2"
rand_distr = "0.6"
bitvec = "1.1"
itertools = "0.15.0"
derive_builder = "0.20"
lexical = "7.0"
bstr = "1.13.1"
lazy_static = "1.5.0"
tempfile = "3.27"
parquet = "60.0"
arrow = "60.0"
colored = "3"
textwrap = "0.16"
flate2 = { version = "1.1.10", features = ["zlib-ng"], default-features = false }

# binaries
clap = { version = "4.6.7", features = ["derive"] }
env_logger = "0.11"
stringzilla = "5.1.2"
human-panic = "2.0"


[build-dependencies]
pyo3-build-config = "0.25"
