_target_: chimera.models.basic_module.ClassificationLit

net:
  _target_: chimera.models.mamba.MambaSequenceClassification
  vocab_size: 12
  embedding_dim: 256
  number_of_layers: 12
  model_max_length: 30000
  dropout: 0.1
  d_state: 16
  d_conv: 4
  expand: 2
  number_of_classes: 2

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss

# compile model for faster training with pytorch 2.0
compile: false
