_target_: chimera.models.basic_module.ClassificationLit

net:
  _target_: chimera.models.mamba.MambaSequenceClassificationSP
  vocab_size: 12
  embedding_dim: 512
  number_of_layers: 3
  dropout: 0.2
  headdim: 64
  d_state: 128
  d_conv: 4
  expand: 3
  number_of_classes: 2

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 6

criterion:
  _target_: torch.nn.CrossEntropyLoss

# compile model for faster training with pytorch 2.0
compile: false
